# Generated by Django 4.1.1 on 2022-09-19 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvelement',
            name='end',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='cvelement',
            name='start',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='cvelement',
            name='descrizione',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='cvelement',
            name='riassunto',
            field=models.CharField(max_length=500),
        ),
    ]
